INSERT OR IGNORE INTO referral_codes (
  id,
  partner_id,
  code,
  status,
  landing_url,
  qr_image_key,
  created_at,
  updated_at
) VALUES
  (
    'rcode_seed_m0369e',
    NULL,
    'M0369E',
    'active',
    'https://wellness.apexcompounding.com/?ref=M0369E',
    NULL,
    datetime('now'),
    datetime('now')
  ),
  (
    'rcode_seed_j3428v',
    NULL,
    'J3428V',
    'active',
    'https://wellness.apexcompounding.com/?ref=J3428V',
    NULL,
    datetime('now'),
    datetime('now')
  );
