export type ResendTemplateCategory =
  | "account"
  | "intake"
  | "order"
  | "shipping"
  | "post_purchase"
  | "support"
  | "referral_partner"
  | "admin";

export type ResendTemplateAudience = "customer" | "partner" | "admin";

export type ResendTemplateDefinition = {
  alias: string;
  name: string;
  subject: string;
  previewText: string;
  category: ResendTemplateCategory;
  audience: ResendTemplateAudience;
  trigger: string;
  requiredVariables: string[];
  description: string;
  ctaLabel: string;
  ctaUrlVariable: string;
  bodyLines: string[];
};

const TEMPLATE_DEFINITIONS = [
  {
    alias: "apex-welcome-account-created",
    name: "Apex Wellness - Welcome Account Created",
    subject: "Welcome to Apex Wellness",
    previewText: "Your account is ready.",
    category: "account",
    audience: "customer",
    trigger: "account created",
    requiredVariables: ["CUSTOMER_NAME", "PORTAL_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Welcome email sent after an Apex Wellness account is created.",
    ctaLabel: "Access Your Account",
    ctaUrlVariable: "PORTAL_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Welcome to Apex Wellness.",
      "Your account has been created, and you can now access your secure portal to complete your intake, view updates, manage orders, and contact support.",
      "For help, contact us at {{{SUPPORT_EMAIL}}}.",
    ],
  },
  {
    alias: "apex-email-verification",
    name: "Apex Wellness - Email Verification",
    subject: "Verify your Apex Wellness email",
    previewText: "Confirm your email address to continue.",
    category: "account",
    audience: "customer",
    trigger: "email verification",
    requiredVariables: ["CUSTOMER_NAME", "VERIFICATION_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Verification email for newly created Apex Wellness accounts.",
    ctaLabel: "Verify Email",
    ctaUrlVariable: "VERIFICATION_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Please verify your email address to complete your Apex Wellness account setup.",
      "If you did not create an Apex Wellness account, you can ignore this email.",
    ],
  },
  {
    alias: "apex-password-reset",
    name: "Apex Wellness - Password Reset",
    subject: "Reset your Apex Wellness password",
    previewText: "Use this secure link to reset your password.",
    category: "account",
    audience: "customer",
    trigger: "password reset",
    requiredVariables: ["CUSTOMER_NAME", "RESET_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Password reset email for Apex Wellness accounts.",
    ctaLabel: "Reset Password",
    ctaUrlVariable: "RESET_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "We received a request to reset your Apex Wellness password.",
      "If you did not request this, no action is needed.",
    ],
  },
  {
    alias: "apex-intake-started-reminder",
    name: "Apex Wellness - Intake Started Reminder",
    subject: "Complete your Apex Wellness intake",
    previewText: "Your intake is saved and ready to finish.",
    category: "intake",
    audience: "customer",
    trigger: "intake abandoned",
    requiredVariables: ["CUSTOMER_NAME", "PORTAL_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Reminder for customers who started intake but have not completed it.",
    ctaLabel: "Continue Intake",
    ctaUrlVariable: "PORTAL_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "You started your Apex Wellness intake but have not completed it yet.",
      "Your progress has been saved. You can return at any time to finish the remaining steps.",
      "For privacy, detailed intake information is only available through your secure account.",
    ],
  },
  {
    alias: "apex-intake-submitted",
    name: "Apex Wellness - Intake Submitted",
    subject: "Your Apex Wellness intake has been received",
    previewText: "We received your submission.",
    category: "intake",
    audience: "customer",
    trigger: "intake submitted",
    requiredVariables: ["CUSTOMER_NAME", "PORTAL_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Confirmation that an Apex Wellness intake was submitted.",
    ctaLabel: "View Status",
    ctaUrlVariable: "PORTAL_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your Apex Wellness intake has been received.",
      "Our team will review the information submitted through your secure portal and update you if anything else is needed.",
    ],
  },
  {
    alias: "apex-additional-info-needed",
    name: "Apex Wellness - Additional Information Needed",
    subject: "Action needed for your Apex Wellness request",
    previewText: "Please log in to provide additional information.",
    category: "intake",
    audience: "customer",
    trigger: "additional info needed",
    requiredVariables: ["CUSTOMER_NAME", "PORTAL_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Request for more information related to a referral or intake.",
    ctaLabel: "View Request",
    ctaUrlVariable: "PORTAL_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Additional information is needed to continue reviewing your Apex Wellness request.",
      "Please log in to your secure account to view the request and submit the required information.",
      "For privacy, details are only shown inside your secure account.",
    ],
  },
  {
    alias: "apex-referral-review-update",
    name: "Apex Wellness - Referral Review Update",
    subject: "Apex Wellness referral update",
    previewText: "An update is available in your account.",
    category: "intake",
    audience: "customer",
    trigger: "referral review update",
    requiredVariables: ["CUSTOMER_NAME", "PORTAL_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Status update related to an Apex Wellness referral review.",
    ctaLabel: "View Update",
    ctaUrlVariable: "PORTAL_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "There is an update regarding your Apex Wellness referral request.",
      "Please log in to your secure account to view the latest status and any next steps.",
    ],
  },
  {
    alias: "apex-order-confirmation",
    name: "Apex Wellness - Order Confirmation",
    subject: "Your Apex Wellness order is confirmed",
    previewText: "Order {{{ORDER_NUMBER}}} has been received.",
    category: "order",
    audience: "customer",
    trigger: "order confirmation",
    requiredVariables: [
      "CUSTOMER_NAME",
      "ORDER_NUMBER",
      "ORDER_TOTAL",
      "SHIPPING_ADDRESS",
      "ORDER_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Confirmation email sent after an order is placed.",
    ctaLabel: "View Order",
    ctaUrlVariable: "ORDER_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Thank you for your order.",
      "We have received your Apex Wellness order and will begin processing it.",
      "Order Number: {{{ORDER_NUMBER}}}",
      "Order Total: {{{ORDER_TOTAL}}}",
      "Shipping To: {{{SHIPPING_ADDRESS}}}",
    ],
  },
  {
    alias: "apex-payment-successful",
    name: "Apex Wellness - Payment Successful",
    subject: "Payment received for your Apex Wellness order",
    previewText: "Your payment was successful.",
    category: "order",
    audience: "customer",
    trigger: "payment success",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "ORDER_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Payment success confirmation for an Apex Wellness order.",
    ctaLabel: "View Order",
    ctaUrlVariable: "ORDER_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your payment for Apex Wellness order {{{ORDER_NUMBER}}} was successfully received.",
      "We will continue processing your order and send another update when it moves forward.",
    ],
  },
  {
    alias: "apex-payment-failed",
    name: "Apex Wellness - Payment Failed",
    subject: "Payment issue with your Apex Wellness order",
    previewText: "Please update your payment method.",
    category: "order",
    audience: "customer",
    trigger: "payment failed",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "PAYMENT_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Payment failure notification with a secure update link.",
    ctaLabel: "Update Payment",
    ctaUrlVariable: "PAYMENT_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "We were unable to complete payment for Apex Wellness order {{{ORDER_NUMBER}}}.",
      "To avoid delays, please update your payment method through your secure account.",
      "If you already resolved this issue, no further action is needed.",
    ],
  },
  {
    alias: "apex-order-processing",
    name: "Apex Wellness - Order Processing",
    subject: "Your Apex Wellness order is being processed",
    previewText: "We are preparing your order.",
    category: "order",
    audience: "customer",
    trigger: "order processing",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "ORDER_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Order processing update.",
    ctaLabel: "View Order",
    ctaUrlVariable: "ORDER_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your Apex Wellness order {{{ORDER_NUMBER}}} is now being processed.",
      "You will receive another email once shipping information becomes available.",
    ],
  },
  {
    alias: "apex-shipping-label-created",
    name: "Apex Wellness - Shipping Label Created",
    subject: "Your Apex Wellness order is getting ready to ship",
    previewText: "Tracking has been created for your order.",
    category: "shipping",
    audience: "customer",
    trigger: "shipping label created",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "TRACKING_NUMBER", "TRACKING_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Tracking label creation notice.",
    ctaLabel: "Track Package",
    ctaUrlVariable: "TRACKING_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "A shipping label has been created for your Apex Wellness order {{{ORDER_NUMBER}}}.",
      "Tracking may take time to update once the carrier receives the package.",
      "Tracking Number: {{{TRACKING_NUMBER}}}",
    ],
  },
  {
    alias: "apex-order-shipped",
    name: "Apex Wellness - Order Shipped",
    subject: "Your Apex Wellness order has shipped",
    previewText: "Your package is on the way.",
    category: "shipping",
    audience: "customer",
    trigger: "order shipped",
    requiredVariables: [
      "CUSTOMER_NAME",
      "ORDER_NUMBER",
      "CARRIER",
      "TRACKING_NUMBER",
      "ESTIMATED_DELIVERY",
      "TRACKING_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Shipment confirmation email with carrier information.",
    ctaLabel: "Track Package",
    ctaUrlVariable: "TRACKING_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your Apex Wellness order {{{ORDER_NUMBER}}} has shipped.",
      "Carrier: {{{CARRIER}}}",
      "Tracking Number: {{{TRACKING_NUMBER}}}",
      "Estimated Delivery: {{{ESTIMATED_DELIVERY}}}",
    ],
  },
  {
    alias: "apex-out-for-delivery",
    name: "Apex Wellness - Out for Delivery",
    subject: "Your Apex Wellness order is out for delivery",
    previewText: "Delivery is expected today.",
    category: "shipping",
    audience: "customer",
    trigger: "out for delivery",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "TRACKING_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Carrier out-for-delivery update.",
    ctaLabel: "Track Package",
    ctaUrlVariable: "TRACKING_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your Apex Wellness order {{{ORDER_NUMBER}}} is out for delivery.",
      "You can track the latest carrier updates using the button below.",
      "If you have delivery concerns, contact us at {{{SUPPORT_EMAIL}}}.",
    ],
  },
  {
    alias: "apex-delivered",
    name: "Apex Wellness - Delivered",
    subject: "Your Apex Wellness order was delivered",
    previewText: "Delivery has been confirmed.",
    category: "shipping",
    audience: "customer",
    trigger: "delivered",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "TRACKING_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Delivery confirmation email.",
    ctaLabel: "Track Package",
    ctaUrlVariable: "TRACKING_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your Apex Wellness order {{{ORDER_NUMBER}}} has been marked as delivered.",
      "If you did not receive your package, please check the tracking details or contact our support team.",
      "Contact Support: {{{SUPPORT_EMAIL}}}",
    ],
  },
  {
    alias: "apex-shipping-delay",
    name: "Apex Wellness - Shipping Delay",
    subject: "Update on your Apex Wellness shipment",
    previewText: "There is a delay with your delivery.",
    category: "shipping",
    audience: "customer",
    trigger: "shipping delay",
    requiredVariables: ["CUSTOMER_NAME", "ORDER_NUMBER", "TRACKING_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Delay notice for a shipment affected in transit.",
    ctaLabel: "Track Package",
    ctaUrlVariable: "TRACKING_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "There is a shipping delay affecting Apex Wellness order {{{ORDER_NUMBER}}}.",
      "You can view the latest carrier updates using the tracking link below.",
      "We will continue monitoring the shipment status.",
    ],
  },
  {
    alias: "apex-product-care-order-info",
    name: "Apex Wellness - Product Care Order Information",
    subject: "Important information about your Apex Wellness order",
    previewText: "Helpful details for your delivered order.",
    category: "post_purchase",
    audience: "customer",
    trigger: "post-delivery info",
    requiredVariables: ["CUSTOMER_NAME", "PORTAL_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Post-delivery guidance directing customers to the secure portal for details.",
    ctaLabel: "View Order Details",
    ctaUrlVariable: "PORTAL_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Your Apex Wellness order has been delivered.",
      "Please review the product packaging and information included with your order. For account-specific details, log in to your secure portal.",
      "For support, contact {{{SUPPORT_EMAIL}}}.",
    ],
  },
  {
    alias: "apex-reorder-reminder",
    name: "Apex Wellness - Reorder Reminder",
    subject: "Time to reorder from Apex Wellness?",
    previewText: "Based on your previous order date, you may be ready.",
    category: "post_purchase",
    audience: "customer",
    trigger: "reorder reminder",
    requiredVariables: [
      "CUSTOMER_NAME",
      "REORDER_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
      "PREFERENCES_LINK",
      "UNSUBSCRIBE_LINK",
    ],
    description: "Optional reorder reminder with preference links.",
    ctaLabel: "View Reorder Options",
    ctaUrlVariable: "REORDER_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Based on your previous Apex Wellness order, you may be ready to reorder.",
      "You can view your past orders and reorder through your secure account.",
      "If you do not need anything right now, no action is required.",
    ],
  },
  {
    alias: "apex-review-request",
    name: "Apex Wellness - Review Request",
    subject: "How was your Apex Wellness experience?",
    previewText: "We would appreciate your feedback.",
    category: "post_purchase",
    audience: "customer",
    trigger: "review request",
    requiredVariables: [
      "CUSTOMER_NAME",
      "REVIEW_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
      "PREFERENCES_LINK",
      "UNSUBSCRIBE_LINK",
    ],
    description: "Post-purchase feedback request with preference links.",
    ctaLabel: "Leave Feedback",
    ctaUrlVariable: "REVIEW_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "Thank you for choosing Apex Wellness.",
      "We would appreciate your feedback on your recent experience, including ordering, packaging, shipping, and support.",
      "Your feedback helps us improve the Apex Wellness experience.",
    ],
  },
  {
    alias: "apex-support-request-confirmation",
    name: "Apex Wellness - Support Request Confirmation",
    subject: "We received your Apex Wellness support request",
    previewText: "Our team will review your message.",
    category: "support",
    audience: "customer",
    trigger: "support form submitted",
    requiredVariables: [
      "CUSTOMER_NAME",
      "TICKET_NUMBER",
      "SUPPORT_TICKET_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Confirmation for a support request submitted through Apex Wellness.",
    ctaLabel: "View Support Request",
    ctaUrlVariable: "SUPPORT_TICKET_LINK",
    bodyLines: [
      "Hi {{{CUSTOMER_NAME}}},",
      "We received your support request.",
      "Request Number: {{{TICKET_NUMBER}}}",
      "Our team will review your message and respond as soon as possible.",
    ],
  },
  {
    alias: "apex-referral-partner-welcome",
    name: "Apex Wellness - Referral Partner Welcome",
    subject: "Welcome to the Apex Wellness referral program",
    previewText: "Your referral account is ready.",
    category: "referral_partner",
    audience: "partner",
    trigger: "referral partner approved",
    requiredVariables: [
      "PARTNER_NAME",
      "REFERRAL_CODE",
      "REFERRAL_LINK",
      "PARTNER_DASHBOARD_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Welcome email for new referral partners.",
    ctaLabel: "Partner Dashboard",
    ctaUrlVariable: "PARTNER_DASHBOARD_LINK",
    bodyLines: [
      "Hi {{{PARTNER_NAME}}},",
      "Welcome to the Apex Wellness referral program.",
      "Your referral account has been created.",
      "Referral Code: {{{REFERRAL_CODE}}}",
      "Referral Link: {{{REFERRAL_LINK}}}",
      "You can use your dashboard to view referral activity, performance, and payout updates.",
    ],
  },
  {
    alias: "apex-new-referral-received",
    name: "Apex Wellness - New Referral Received",
    subject: "New Apex Wellness referral submitted",
    previewText: "A new referral was submitted using your link or code.",
    category: "referral_partner",
    audience: "partner",
    trigger: "new referral received",
    requiredVariables: ["PARTNER_NAME", "PARTNER_DASHBOARD_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Partner notification when a new referral arrives.",
    ctaLabel: "View Referral Activity",
    ctaUrlVariable: "PARTNER_DASHBOARD_LINK",
    bodyLines: [
      "Hi {{{PARTNER_NAME}}},",
      "A new referral has been submitted using your Apex Wellness referral link or code.",
      "You can view the current status inside your partner dashboard.",
      "For privacy, individual customer details may be limited.",
    ],
  },
  {
    alias: "apex-referral-conversion",
    name: "Apex Wellness - Referral Conversion",
    subject: "Apex Wellness referral conversion update",
    previewText: "One of your referrals has converted.",
    category: "referral_partner",
    audience: "partner",
    trigger: "referral converted",
    requiredVariables: ["PARTNER_NAME", "PARTNER_DASHBOARD_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Partner update after a referral converts.",
    ctaLabel: "View Dashboard",
    ctaUrlVariable: "PARTNER_DASHBOARD_LINK",
    bodyLines: [
      "Hi {{{PARTNER_NAME}}},",
      "One of your Apex Wellness referrals has converted.",
      "You can view the updated referral status and commission details inside your partner dashboard.",
    ],
  },
  {
    alias: "apex-commission-earned",
    name: "Apex Wellness - Commission Earned",
    subject: "Referral commission earned",
    previewText: "A commission has been added to your account.",
    category: "referral_partner",
    audience: "partner",
    trigger: "commission earned",
    requiredVariables: [
      "PARTNER_NAME",
      "COMMISSION_AMOUNT",
      "REFERRAL_CODE",
      "COMMISSION_STATUS",
      "PARTNER_DASHBOARD_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Partner commission-earned notification.",
    ctaLabel: "Partner Dashboard",
    ctaUrlVariable: "PARTNER_DASHBOARD_LINK",
    bodyLines: [
      "Hi {{{PARTNER_NAME}}},",
      "A referral commission has been added to your Apex Wellness partner account.",
      "Commission Amount: {{{COMMISSION_AMOUNT}}}",
      "Referral Code: {{{REFERRAL_CODE}}}",
      "Status: {{{COMMISSION_STATUS}}}",
    ],
  },
  {
    alias: "apex-payout-scheduled",
    name: "Apex Wellness - Payout Scheduled",
    subject: "Your Apex Wellness payout is scheduled",
    previewText: "Your referral payout is being prepared.",
    category: "referral_partner",
    audience: "partner",
    trigger: "payout scheduled",
    requiredVariables: ["PARTNER_NAME", "PAYOUT_AMOUNT", "PAYOUT_DATE", "PARTNER_DASHBOARD_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Partner payout scheduling email.",
    ctaLabel: "View Payouts",
    ctaUrlVariable: "PARTNER_DASHBOARD_LINK",
    bodyLines: [
      "Hi {{{PARTNER_NAME}}},",
      "Your Apex Wellness referral payout has been scheduled.",
      "Payout Amount: {{{PAYOUT_AMOUNT}}}",
      "Estimated Payout Date: {{{PAYOUT_DATE}}}",
    ],
  },
  {
    alias: "apex-monthly-referral-summary",
    name: "Apex Wellness - Monthly Referral Summary",
    subject: "Your monthly Apex Wellness referral summary",
    previewText: "Review your monthly referral performance.",
    category: "referral_partner",
    audience: "partner",
    trigger: "monthly referral summary",
    requiredVariables: [
      "PARTNER_NAME",
      "MONTH",
      "CLICK_COUNT",
      "REFERRAL_COUNT",
      "CONVERSION_COUNT",
      "PENDING_COMMISSIONS",
      "PAID_COMMISSIONS",
      "PARTNER_DASHBOARD_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Monthly partner performance summary.",
    ctaLabel: "Partner Dashboard",
    ctaUrlVariable: "PARTNER_DASHBOARD_LINK",
    bodyLines: [
      "Hi {{{PARTNER_NAME}}},",
      "Here is your Apex Wellness referral summary for {{{MONTH}}}:",
      "Referral Clicks: {{{CLICK_COUNT}}}",
      "Referrals Submitted: {{{REFERRAL_COUNT}}}",
      "Converted Referrals: {{{CONVERSION_COUNT}}}",
      "Pending Commissions: {{{PENDING_COMMISSIONS}}}",
      "Paid Commissions: {{{PAID_COMMISSIONS}}}",
    ],
  },
  {
    alias: "apex-admin-new-intake-submitted",
    name: "Apex Wellness Admin - New Intake Submitted",
    subject: "New Apex Wellness intake submitted",
    previewText: "A new intake is ready for review.",
    category: "admin",
    audience: "admin",
    trigger: "internal new intake",
    requiredVariables: ["CUSTOMER_NAME", "CUSTOMER_EMAIL", "SUBMITTED_AT", "ADMIN_LINK", "SUPPORT_EMAIL", "WEBSITE_URL"],
    description: "Internal admin notification when a new intake is submitted.",
    ctaLabel: "View Intake",
    ctaUrlVariable: "ADMIN_LINK",
    bodyLines: [
      "A new Apex Wellness intake has been submitted.",
      "Customer: {{{CUSTOMER_NAME}}}",
      "Email: {{{CUSTOMER_EMAIL}}}",
      "Submitted At: {{{SUBMITTED_AT}}}",
    ],
  },
  {
    alias: "apex-admin-new-order-placed",
    name: "Apex Wellness Admin - New Order Placed",
    subject: "New Apex Wellness order placed",
    previewText: "Order {{{ORDER_NUMBER}}} has been received.",
    category: "admin",
    audience: "admin",
    trigger: "internal new order",
    requiredVariables: [
      "ORDER_NUMBER",
      "CUSTOMER_NAME",
      "ORDER_TOTAL",
      "PAYMENT_STATUS",
      "ADMIN_ORDER_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Internal admin notification for a new order.",
    ctaLabel: "View Order",
    ctaUrlVariable: "ADMIN_ORDER_LINK",
    bodyLines: [
      "A new Apex Wellness order has been placed.",
      "Order Number: {{{ORDER_NUMBER}}}",
      "Customer: {{{CUSTOMER_NAME}}}",
      "Order Total: {{{ORDER_TOTAL}}}",
      "Payment Status: {{{PAYMENT_STATUS}}}",
    ],
  },
  {
    alias: "apex-admin-payment-failed",
    name: "Apex Wellness Admin - Payment Failed",
    subject: "Payment failed for Apex Wellness order {{{ORDER_NUMBER}}}",
    previewText: "Customer payment requires attention.",
    category: "admin",
    audience: "admin",
    trigger: "internal payment failed",
    requiredVariables: [
      "ORDER_NUMBER",
      "CUSTOMER_NAME",
      "CUSTOMER_EMAIL",
      "FAILURE_REASON",
      "ADMIN_ORDER_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Internal alert for an order payment failure.",
    ctaLabel: "View Order",
    ctaUrlVariable: "ADMIN_ORDER_LINK",
    bodyLines: [
      "Payment failed for an Apex Wellness order.",
      "Order Number: {{{ORDER_NUMBER}}}",
      "Customer: {{{CUSTOMER_NAME}}}",
      "Email: {{{CUSTOMER_EMAIL}}}",
      "Failure Reason: {{{FAILURE_REASON}}}",
    ],
  },
  {
    alias: "apex-admin-low-inventory",
    name: "Apex Wellness Admin - Low Inventory",
    subject: "Low inventory alert: {{{PRODUCT_NAME}}}",
    previewText: "Stock has reached the low inventory threshold.",
    category: "admin",
    audience: "admin",
    trigger: "low inventory",
    requiredVariables: [
      "PRODUCT_NAME",
      "CURRENT_STOCK",
      "STOCK_THRESHOLD",
      "SKU",
      "INVENTORY_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Internal low inventory alert.",
    ctaLabel: "View Inventory",
    ctaUrlVariable: "INVENTORY_LINK",
    bodyLines: [
      "Inventory for {{{PRODUCT_NAME}}} has reached the low-stock threshold.",
      "Current Stock: {{{CURRENT_STOCK}}}",
      "Threshold: {{{STOCK_THRESHOLD}}}",
      "SKU: {{{SKU}}}",
    ],
  },
  {
    alias: "apex-admin-high-risk-order-review",
    name: "Apex Wellness Admin - High Risk Order Review",
    subject: "Order requires review: {{{ORDER_NUMBER}}}",
    previewText: "A risk flag was detected.",
    category: "admin",
    audience: "admin",
    trigger: "high-risk order",
    requiredVariables: [
      "ORDER_NUMBER",
      "CUSTOMER_NAME",
      "ORDER_TOTAL",
      "RISK_REASON",
      "FRAUD_SCORE",
      "ADMIN_ORDER_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Internal review request for a flagged order.",
    ctaLabel: "Review Order",
    ctaUrlVariable: "ADMIN_ORDER_LINK",
    bodyLines: [
      "Apex Wellness order {{{ORDER_NUMBER}}} requires review.",
      "Customer: {{{CUSTOMER_NAME}}}",
      "Order Total: {{{ORDER_TOTAL}}}",
      "Risk Reason: {{{RISK_REASON}}}",
      "Fraud Score: {{{FRAUD_SCORE}}}",
    ],
  },
  {
    alias: "apex-admin-new-support-request",
    name: "Apex Wellness Admin - New Support Request",
    subject: "New Apex Wellness support request",
    previewText: "A customer submitted a support message.",
    category: "admin",
    audience: "admin",
    trigger: "new support request",
    requiredVariables: [
      "CUSTOMER_NAME",
      "CUSTOMER_EMAIL",
      "TICKET_NUMBER",
      "SUPPORT_CATEGORY",
      "SUPPORT_TICKET_LINK",
      "SUPPORT_EMAIL",
      "WEBSITE_URL",
    ],
    description: "Internal support team notification for a new request.",
    ctaLabel: "View Request",
    ctaUrlVariable: "SUPPORT_TICKET_LINK",
    bodyLines: [
      "A new support request has been submitted.",
      "Customer: {{{CUSTOMER_NAME}}}",
      "Email: {{{CUSTOMER_EMAIL}}}",
      "Request Number: {{{TICKET_NUMBER}}}",
      "Category: {{{SUPPORT_CATEGORY}}}",
    ],
  },
] as const satisfies readonly ResendTemplateDefinition[];

export type ResendTemplateAlias = (typeof TEMPLATE_DEFINITIONS)[number]["alias"];

export const RESEND_TEMPLATE_LIST = [...TEMPLATE_DEFINITIONS];

export const RESEND_TEMPLATES = Object.freeze(
  Object.fromEntries(
    RESEND_TEMPLATE_LIST.map((template) => [template.alias, template]),
  ) as unknown as Record<ResendTemplateAlias, ResendTemplateDefinition>,
);

export function isResendTemplateAlias(value: string): value is ResendTemplateAlias {
  return value in RESEND_TEMPLATES;
}
