export const REFERRAL_ACCESS_DISCOUNT_PERCENT = 15;
export const REFERRAL_ACCESS_DISCOUNT_RATE = REFERRAL_ACCESS_DISCOUNT_PERCENT / 100;
export const DEFAULT_REFERRAL_COMMISSION_TYPE = "percentage";
export const DEFAULT_REFERRAL_COMMISSION_VALUE = 15;
